// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NotificationDetailModelisadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NotificationDetailModelisadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201909021725349_Notification Detail Model is added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
